plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.ab.droid.jpref'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.ab.droid.jpref"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "long", "TIMESTAMP", System.currentTimeMillis() + "L"
        buildConfigField "String", "ROOT_PROJECT_NAME", "\"${rootProject.name}\""
    }

    buildTypes {
        release {
            shrinkResources false
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
         buildConfig = true
   }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation project(':jpref-engine')
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
